
export const ORDERS_CHART_REQUEST = "ORDERS_CHART_REQUEST";
export const ORDERS_CHART_SUCCESS = "ORDERS_CHART_SUCCESS";
export const ORDERS_CHART_RESET = "ORDERS_CHART_RESET";
export const ORDERS_CHART_FAIL = "ORDERS_CHART_FAIL";

export const SALES_CHART_REQUEST = "SALES_CHART_REQUEST";
export const SALES_CHART_SUCCESS = "SALES_CHART_SUCCESS";
export const SALES_CHART_RESET = "SALES_CHART_RESET";
export const SALES_CHART_FAIL = "SALES_CHART_FAIL";

export const SALES_PER_DAY_REQUEST = "SALES_PER_DAY_REQUEST";
export const SALES_PER_DAY_SUCCESS = "SALES_PER_DAY_SUCCESS";
export const SALES_PER_DAY_RESET = "SALES_PER_DAY_RESET";
export const SALES_PER_DAY_FAIL = "SALES_PER_DAY_FAIL";

export const ORDER_PER_DAY_REQUEST = "ORDER_PER_DAY_REQUEST";
export const ORDER_PER_DAY_SUCCESS = "ORDER_PER_DAY_SUCCESS";
export const ORDER_PER_DAY_RESET = "ORDER_PER_DAY_RESET";
export const ORDER_PER_DAY_FAIL = "ORDER_PER_DAY_FAIL";


export const CLEAR_ERRORS = "CLEAR_ERRORS";