
export const ADD_COUPON_REQUEST = "ADD_COUPON_REQUEST";
export const ADD_COUPON_SUCCESS = "ADD_COUPON_SUCCESS";
export const ADD_COUPON_RESET = "ADD_COUPON_RESET";
export const ADD_COUPON_FAIL = "ADD_COUPON_FAIL";

export const DELETE_COUPON_REQUEST = "DELETE_COUPON_REQUEST";
export const DELETE_COUPON_SUCCESS = "DELETE_COUPON_SUCCESS";
export const DELETE_COUPON_RESET = "DELETE_COUPON_RESET";
export const DELETE_COUPON_FAIL = "DELETE_COUPON_FAIL";

export const ALL_COUPONS_REQUEST = "ALL_COUPONS_REQUEST";
export const ALL_COUPONS_SUCCESS = "ALL_COUPONS_SUCCESS";
export const ALL_COUPONS_FAIL = "ALL_COUPONS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";