export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL";

export const MY_ORDERS_REQUEST = "MY_ORDERS_REQUEST";
export const MY_ORDERS_SUCCESS = "MY_ORDERS_SUCCESS";
export const MY_ORDERS_FAIL = "MY_ORDERS_FAIL";

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL";

export const ALL_ORDERS_REQUEST = "ALL_ORDERS_REQUEST";
export const ALL_ORDERS_SUCCESS = "ALL_ORDERS_SUCCESS";
export const ALL_ORDERS_FAIL = "ALL_ORDERS_FAIL";

export const UPDATE_ORDER_REQUEST = "UPDATE_ORDER_REQUEST";
export const UPDATE_ORDER_SUCCESS = "UPDATE_ORDER_SUCCESS";
export const UPDATE_ORDER_FAIL = "UPDATE_ORDER_FAIL";
export const UPDATE_ORDER_RESET = "UPDATE_ORDER_RESET";

export const DELETE_ORDER_REQUEST = "DELETE_ORDER_REQUEST";
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS";
export const DELETE_ORDER_FAIL = "DELETE_ORDER_FAIL";
export const DELETE_ORDER_RESET = "DELETE_ORDER_RESET";

export const USER_ORDERS_REQUEST = "USER_ORDERS_REQUEST" ;
export const USER_ORDERS_SUCCESS = "USER_ORDERS_SUCCESS" ;
export const USER_ORDERS_RESET = "USER_ORDERS_RESET" ;
export const USER_ORDERS_FAIL =    "USER_ORDERS_FAIL" ;

export const ADD_ORDER_NOTE_REQUEST = "ADD_ORDER_NOTE_REQUEST" ;
export const ADD_ORDER_NOTE_SUCCESS = "ADD_ORDER_NOTE_SUCCESS" ;
export const ADD_ORDER_NOTE_RESET = "ADD_ORDER_NOTE_RESET" ;
export const ADD_ORDER_NOTE_FAIL =    "ADD_ORDER_NOTE_FAIL" ;

export const DELETE_ORDER_NOTE_REQUEST = "DELETE_ORDER_NOTE_REQUEST" ;
export const DELETE_ORDER_NOTE_SUCCESS = "DELETE_ORDER_NOTE_SUCCESS" ;
export const DELETE_ORDER_NOTE_RESET = "DELETE_ORDER_NOTE_RESET" ;
export const DELETE_ORDER_NOTE_FAIL =    "DELETE_ORDER_NOTE_FAIL" ;

export const CANCEL_ORDER_NOTE_REQUEST = "CANCEL_ORDER_NOTE_REQUEST" ;
export const CANCEL_ORDER_NOTE_SUCCESS = "CANCEL_ORDER_NOTE_SUCCESS" ;
export const CANCEL_ORDER_NOTE_RESET = "CANCEL_ORDER_NOTE_RESET" ;
export const CANCEL_ORDER_NOTE_FAIL =    "CANCEL_ORDER_NOTE_FAIL" ;

export const ACTIVE_ORDER_NOTE_REQUEST = "ACTIVE_ORDER_NOTE_REQUEST" ;
export const ACTIVE_ORDER_NOTE_SUCCESS = "ACTIVE_ORDER_NOTE_SUCCESS" ;
export const ACTIVE_ORDER_NOTE_RESET = "ACTIVE_ORDER_NOTE_RESET" ;
export const ACTIVE_ORDER_NOTE_FAIL =    "ACTIVE_ORDER_NOTE_FAIL" ;


export const CLEAR_ERRORS = "CLEAR_ERRORS";